/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface LanguageInfo {
  lang: string
  files: number
  lines: number
  code: number
  comments: number
  blanks: number
  reports?: Array<Report>
}

export interface Report {
  name: string
  lines: number
  code: number
  comments: number
  blanks: number
}

export declare function tokei(options: TokeiOptions): Array<LanguageInfo>

export interface TokeiOptions {
  include?: Array<string>
  exclude?: Array<string>
  languages?: Array<string>
  hidden?: boolean
  noIgnore?: boolean
  noIgnoreParent?: boolean
  noIgnoreDot?: boolean
  noIgnoreVcs?: boolean
  treatDocStringsAsComments?: boolean
  files?: boolean
}
