/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CodeStatus {
  blanks: number
  code: number
  comments: number
}

export interface LanguageInfo {
  lang: string
  files: number
  lines: number
  code: number
  comments: number
  blanks: number
}

export interface Report {
  name: string
  status: Array<CodeStatus>
}

export declare function tokei(options: TokeiOptions): Array<LanguageInfo>

export interface TokeiOptions {
  include?: Array<string>
  exclude?: Array<string>
  languages?: Array<string>
}
